export const actionType = {
  COURSES_ALL_LOADING: 'COURSES_ALL_LOADING',
  COURSES_ALL_SUCCESS: 'COURSES_ALL_SUCCESS',
  COURSES_ALL_FAILED: 'COURSES_ALL_FAILED',

  BOOKMARKED_COURSES_ALL_LOADING: 'BOOKMARKED_COURSES_ALL_LOADING',
  BOOKMARKED_COURSES_ALL_SUCCESS: 'BOOKMARKED_COURSES_ALL_SUCCESS',
  BOOKMARKED_COURSES_ALL_FAILED: 'BOOKMARKED_COURSES_ALL_FAILED',

  TIMELINE_COURSES_ALL_LOADING: 'TIMELINE_COURSES_ALL_LOADING',
  TIMELINE_COURSES_ALL_SUCCESS: 'TIMELINE_COURSES_ALL_SUCCESS',
  TIMELINE_COURSES_ALL_FAILED: 'TIMELINE_COURSES_ALL_FAILED',

  COURSE_LIKE_LOADING: 'COURSE_LIKE_LOADING',
  COURSE_LIKE_SUCCESS: 'COURSE_LIKE_SUCCESS',
  COURSE_LIKE_FAILED: 'COURSE_LIKE_FAILED',

  SAMPLE_VIDEOS_ALL_LOADING: 'SAMPLE_VIDEOS_ALL_LOADING',
  SAMPLE_VIDEOS_ALL_SUCCESS: 'SAMPLE_VIDEOS_ALL_SUCCESS',
  SAMPLE_VIDEOS_ALL_FAILED: 'SAMPLE_VIDEOS_ALL_FAILED',

  GET_COURSE_DETAILS_LOADING: 'GET_COURSE_DETAILS_LOADING',
  GET_COURSE_DETAILS_SUCCESS: 'GET_COURSE_DETAILS_SUCCESS',
  GET_COURSE_DETAILS_FAILED: 'GET_COURSE_DETAILS_FAILED',
};
