export const actionType = {
    
    GET_LESSONS_BY_COURSE_LOADING: 'GET_LESSONS_BY_COURSE_LOADING',
    GET_LESSONS_BY_COURSE_SUCCESS:'GET_LESSONS_BY_COURSE_SUCCESS',
    GET_LESSONS_BY_COURSE_FAILED:'GET_LESSONS_BY_COURSE_FAILED',

    UPDATE_LESSONS_WATCHIG_STATUS_LOADING: 'UPDATE_LESSONS_WATCHIG_STATUS_LOADING',
    UPDATE_LESSONS_WATCHIG_STATUS_SUCCESS:'UPDATE_LESSONS_WATCHIG_STATUS_SUCCESS',
    UPDATE_LESSONS_WATCHIG_STATUS_FAILED:'UPDATE_LESSONS_WATCHIG_STATUS_FAILED',

    ADD_BOOK_MARK_LOADING: 'ADD_BOOK_MARK_LOADING',
    ADD_BOOK_MARK_SUCCESS:'ADD_BOOK_MARK_SUCCESS',
    ADD_BOOK_MARK_FAILED:'ADD_BOOK_MARK_FAILED',

    UPDATE_RATING_LOADING: 'UPDATE_RATING_LOADING',
    UPDATE_RATING_SUCCESS:'UPDATE_RATING_SUCCESS',
    UPDATE_RATING_FAILED:'UPDATE_RATING_FAILED',
  
    LESSON_LIKE_LOADING: 'LESSON_LIKE_LOADING',
    LESSON_LIKE_SUCCESS:'LESSON_LIKE_SUCCESS',
    LESSON_LIKE_FAILED:'LESSON_LIKE_FAILED',

    LESSON_REVIEW_LOADING: 'LESSON_REVIEW_LOADING',
    LESSON_REVIEW_SUCCESS:'LESSON_REVIEW_SUCCESS',
    LESSON_REVIEW_FAILED:'LESSON_REVIEW_FAILED',
};
  