export const actionType = {
    HOME_SAMPLE_VIDEOS_LOADING: 'HOME_SAMPLE_VIDEOS_LOADING',
    HOME_SAMPLE_VIDEOS_SUCCESS: 'HOME_SAMPLE_VIDEOS_SUCCESS',
    HOME_SAMPLE_VIDEOS_FAILED: 'HOME_SAMPLE_VIDEOS_FAILED',

    HOME_RANDOM_TOPIC_LOADING: 'HOME_RANDOM_TOPIC_LOADING',
    HOME_RANDOM_TOPIC_SUCCESS: 'HOME_RANDOM_TOPIC_SUCCESS',
    HOME_RANDOM_TOPIC_FAILED: 'HOME_RANDOM_TOPIC_FAILED',

    CURRENT_ROUTE:'CURRENT_ROUTE',

    GET_TRENDING_LESSONS_LOADING :"GET_TRENDING_LESSONS_LOADING",
    GET_TRENDING_LESSONS_SUCCESS :"GET_TRENDING_LESSONS_SUCCESS",
    GET_TRENDING_LESSONS_FAILED :"GET_TRENDING_LESSONS_FAILED",

    GET_MOST_WATCED_LESSONS_LOADING :"GET_MOST_WATCED_LESSONS_LOADING",
    GET_MOST_WATCED_LESSONS_SUCCESS :"GET_MOST_WATCED_LESSONS_SUCCESS",
    GET_MOST_WATCED_LESSONS_FAILED :"GET_MOST_WATCED_LESSONS_FAILED",
  };
  
