export const actionType = {
    ADD_QUESTION_LOADING: 'ADD_QUESTION_LOADING',
    ADD_QUESTION_SUCCESS:'ADD_QUESTION_SUCCESS',
    ADD_QUESTION_FAILED:'ADD_QUESTION_FAILED',
    
    VIEW_QUESTION_LOADING: 'VIEW_QUESTION_LOADING',
    VIEW_QUESTION_SUCCESS:'VIEW_QUESTION_SUCCESS',
    VIEW_QUESTION_FAILED:'VIEW_QUESTION_FAILED',
};