export const actionType = {
  AUTH_LOADING: 'AUTH_LOADING',
  
  AUTH_LOGIN_LOADING: 'AUTH_LOGIN_LOADING',
  AUTH_LOGIN_SUCCESS:'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED:'AUTH_LOGIN_FAILED',
  
  AUTH_SIGNUP_LOADING: 'AUTH_SIGNUP_LOADING',
  AUTH_SIGNUP_SUCCESS: 'AUTH_SIGNUP_SUCCESS',
  AUTH_SIGNUP_FAILED: 'AUTH_SIGNUP_FAILED',

  AUTH_LANGUAGE_LOADING: 'AUTH_LANGUAGE_LOADING',
  AUTH_LANGUAGE_SUCCESS:'AUTH_LANGUAGE_SUCCESS',
  AUTH_LANGUAGE_FAILED:'AUTH_LANGUAGE_FAILED',

  AUTH_LOGOUT_LOADING: 'AUTH_LOGOUT_LOADING',
  AUTH_LOGOUT_SUCCESS:'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAILED:'AUTH_LOGOUT_FAILED',

  AUTH_RESET_PASSWORD_LOADING: 'AUTH_RESET_PASSWORD_LOADING',
  AUTH_RESET_PASSWORD_SUCCESS:'AUTH_RESET_PASSWORD_SUCCESS',
  AUTH_RESET_PASSWORD_FAILED:'AUTH_RESET_PASSWORD_FAILED',

  PRO_PIC_LOADING: 'PRO_PIC_LOADING',
  PRO_PIC_SUCCESS:'PRO_PIC_SUCCESS',
  PRO_PIC_FAILED:'PRO_PIC_FAILED',
  
  AUTH_USER:'AUTH_USER',
  AUTH_USER_FAILED:'AUTH_USER_FAILED',
  
  AUTH_CHANGE_PASSWORD_LOADING: 'AUTH_RESET_PASSWORD_LOADING',
  AUTH_CHANGE_PASSWORD_SUCCESS:'AUTH_RESET_PASSWORD_SUCCESS',
  AUTH_CHANGE_PASSWORD_FAILED:'AUTH_RESET_PASSWORD_FAILED',
  
  AUTH_TOKEN:'AUTH_TOKEN',
  RESET_AUTH: 'RESET_AUTH',
  AUTH_CURRENT_LANGUAGE:"AUTH_CURRENT_LANGUAGE"
};
